file = miSudoku


$(file): $(file).pl
	swipl -q -O -g main --stand_alone=true -o $(file) -c $(file).pl


miLiga:	miLiga.pl
		swipl -q -O -g main --stand_alone=true -o miLiga -c miLiga.pl

miHorari: miHorari.pl
		swipl -q -O -g main --stand_alone=true -o miHorari -c miHorari.pl
		
miFlow: miFlow.pl
		swipl -q -O -g main --stand_alone=true -o miFlow -c miFlow.pl

miHorariMejorado: miHorariMejorado.pl
		swipl -q -O -g main --stand_alone=true -o miHorariMejorado -c miHorariMejorado.pl